server:
  port: 8090
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 10

spring.cloud.stream:
  function:
    definition: orderEventPublisher;shippingEventPublisher;orderEventProcessor;shippingEventProcessor;paymentEventConsumer;shippingEventConsumer;inventoryEventProcessor;inventoryEventConsumer
  bindings:
    orderEventPublisher-out-0:
      destination: order-events
    orderEventProcessor-in-0:
      destination: order-events
    orderEventProcessor-out-0:
      destination: payment-events
    paymentEventConsumer-in-0:
      destination: payment-events
    shippingEventPublisher-out-0:
      destination: shippingafterpayment-events
    shippingEventProcessor-in-0:
      destination: shippingafterpayment-events
    shippingEventProcessor-out-0:
      destination: shipping-events
    shippingEventConsumer-in-0:
      destination: shipping-events
    inventoryEventProcessor-in-0:
      destination: inventory-events
    inventoryEventProcessor-out-0:
      destination: inventory-events
    inventoryEventConsumer-in-0:
      destination: inventory-events

